name: Push/PR main

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - "docs"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v3.1.2
      if: github.event_name != 'pull_request'
      with:
        name: dist
        path: dist/avividlogo

  deploy_dev:
    if: github.event_name != 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - uses: actions/download-artifact@v3.0.2
        with:
          name: dist
          path: dist/avividlogo
      - run: sudo npm i -g firebase-tools
      - run: firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy_stg:
    if: github.event_name != 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - uses: actions/download-artifact@v3.0.2
        with:
          name: dist
          path: dist/avividlogo
      - run: sudo npm i -g firebase-tools
      - run: firebase use stg --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - run: firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
  deploy_prod:
    if: github.event_name != 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - uses: actions/download-artifact@v3.0.2
        with:
          name: dist
          path: dist/avividlogo
      - run: sudo npm i -g firebase-tools
      - run: firebase use prod --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - run: firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
